name = "krishi-ai-gateway"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "api.krishiai.live/*"
zone_name = "krishiai.live"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "KRISHI_KV"
id = "366ebccefc354a67b95ad90b53aa0f5e"

[observability.logs]
enabled = true
invocation_logs = true
